"""Command-line interface for BioInsight-AI.

Usage:
    bioinsight gwas results.csv
    bioinsight gwas results.csv --outdir report/ --threshold 5e-8
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from . import __version__, ai, gwas


def _build_report(result: gwas.GwasResult, interpretation: str, plot_path: Path) -> str:
    """Render a Markdown summary report."""
    top = result.top_hits[["snp", "chr", "bp", "p", "neg_log10_p"]].copy()
    top["p"] = top["p"].map(lambda v: f"{v:.3e}")
    top["neg_log10_p"] = top["neg_log10_p"].map(lambda v: f"{v:.2f}")
    top_md = top.to_markdown(index=False)

    return f"""# GWAS Summary Report

_Generated by BioInsight-AI v{__version__}_

## Overview

| Metric | Value |
| --- | --- |
| Variants tested | {result.n_snps:,} |
| Chromosomes | {len(result.chromosomes)} |
| Genome-wide significant (p ≤ {result.threshold:g}) | {result.n_significant} |
| Suggestive (p ≤ {gwas.SUGGESTIVE_THRESHOLD:g}) | {result.n_suggestive} |
| Genomic inflation (λ) | {result.lambda_gc:.3f} |

## AI-assisted interpretation

{interpretation}

## Top hits

{top_md}

## Manhattan plot

![Manhattan plot]({plot_path.name})
"""


def _cmd_gwas(args: argparse.Namespace) -> int:
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    print(f"Loading GWAS results from {args.file} ...")
    df = gwas.load_gwas(args.file)

    print(f"Analyzing {len(df):,} variants ...")
    result = gwas.analyze(df, threshold=args.threshold, top_n=args.top_n)

    plot_path = outdir / "manhattan.png"
    print("Rendering Manhattan plot ...")
    gwas.manhattan_plot(result, plot_path)

    interpretation = ai.interpret_gwas(result)
    report = _build_report(result, interpretation, plot_path)
    report_path = outdir / "report.md"
    report_path.write_text(report)

    # Console summary.
    print()
    print("=" * 60)
    print(f"  Variants tested:        {result.n_snps:,}")
    print(f"  Genome-wide significant: {result.n_significant}")
    print(f"  Suggestive:              {result.n_suggestive}")
    print(f"  Genomic inflation (λ):   {result.lambda_gc:.3f}")
    print("=" * 60)
    print()
    print(interpretation)
    print()
    print(f"Report written to: {report_path}")
    print(f"Plot written to:   {plot_path}")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="bioinsight",
        description="AI-powered bioinformatics toolkit for interpretable insights.",
    )
    parser.add_argument(
        "--version", action="version", version=f"%(prog)s {__version__}"
    )
    sub = parser.add_subparsers(dest="command", required=True)

    g = sub.add_parser("gwas", help="Analyze a GWAS results file.")
    g.add_argument("file", help="Path to GWAS results (CSV or TSV).")
    g.add_argument(
        "-o", "--outdir", default="bioinsight_report", help="Output directory."
    )
    g.add_argument(
        "-t",
        "--threshold",
        type=float,
        default=gwas.GENOME_WIDE_THRESHOLD,
        help="Genome-wide significance threshold (default: 5e-8).",
    )
    g.add_argument(
        "-n", "--top-n", type=int, default=10, help="Number of top hits to report."
    )
    g.set_defaults(func=_cmd_gwas)
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        return args.func(args)
    except (FileNotFoundError, ValueError, NotImplementedError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
