"""Markdown report rendering for a GWAS summary."""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from . import __version__


def render_markdown(summary, interpretation: str, plots: dict) -> str:
    """Render a Markdown summary report.

    ``plots`` maps a label -> Path of an image to embed.
    """
    res = summary.primary
    top = summary.top_hits.copy()
    cols = [c for c in ["snp", "chr", "bp", "p", "p_adj"] if c in top.columns]
    top = top[cols]
    if "p" in top:
        top["p"] = top["p"].map(lambda v: f"{v:.3e}")
    if "p_adj" in top:
        top["p_adj"] = top["p_adj"].map(
            lambda v: "" if pd.isna(v) else f"{v:.3e}"
        )
    top_md = top.to_markdown(index=False)

    # Comparison of significant counts across all threshold methods.
    comp_rows = "\n".join(
        f"| {label} | {n} |" for label, n in summary.method_comparison.items()
    )

    plots_md = "\n\n".join(
        f"### {label}\n\n![{label}]({Path(p).name})" for label, p in plots.items()
    )

    return f"""# GWAS Summary Report

_Generated by BioInsight v{__version__}_

## Overview

| Metric | Value |
| --- | --- |
| Variants tested | {summary.n_snps:,} |
| Chromosomes | {summary.n_chromosomes} |
| Significance method | {res.label} |
| Significant markers | {res.n_significant} |
| Genomic inflation (λ) | {summary.lambda_gc:.3f} |

## Interpretation

{interpretation}

## Significant markers by method

| Method | Significant |
| --- | --- |
{comp_rows}

## Top hits

{top_md}

## Plots

{plots_md}
"""
